### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/awesome-star-count#1]
- [ ] Make into a proper CLI (using StructOpt or Clap v3).
- [ ] Prune tree nodes that have no GitHub links.
- [ ] Add `--flatten` option to ignore heading tree structure.
- [ ] Add `--min-count` option to filter out low star count repositories.
- [ ] Improve output (maybe some colors?).
